version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo "Running pre-build steps..."
      - mvn clean
  build:
    commands:
      - echo "Building and testing the project..."
      - mvn install
  post_build:
    commands:
      - echo "Build and test completed successfully."
artifacts:
  files:
    - target/*.jar
