version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Starting pre-build stage..."
      - mvn clean install -DskipTests
  build:
    commands:
      - echo "Running tests and generating JaCoCo coverage..."
      - mvn test
      - mvn jacoco:report
  post_build:
    commands:
      - echo "Code coverage report generated successfully."
      - ls -lah target/site/jacoco/  # Debugging to ensure files exist

artifacts:
  files:
    - target/site/jacoco/**/*
  discard-paths: no
