version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Starting pre-build stage..."
      - mvn clean install -DskipTests
  build:
    commands:
      - echo "Running tests and generating JaCoCo coverage..."
      - mvn test jacoco:report
  post_build:
    commands:
      - echo "Generating code coverage report..."
      - mvn jacoco:report
      - echo "Build and analysis completed!"

artifacts:
  files:
    - target/site/jacoco/index.html
    - target/site/jacoco/jacoco.xml
  discard-paths: yes
