version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo "Cleaning and preparing build..."
      - mvn clean
  build:
    commands:
      - echo "Building project..."
      - mvn compile
      - echo "Running tests..."
      - mvn test
  post_build:
    commands:
      - echo "Build and test completed successfully."
artifacts:
  files:
    - target/*.jar
