version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Update this based on your Java version
    commands:
      - echo "Installing dependencies..."
      - mvn clean install -DskipTests

  pre_build:
    commands:
      - echo "Running pre-build steps..."
      - mvn validate
      - mvn dependency:resolve

  build:
    commands:
      - echo "Compiling and running tests..."
      - mvn clean verify

  post_build:
    commands:
      - echo "Build completed successfully."
      - mvn package

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
