version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "Starting pre-build stage..."
      - mvn clean install -DskipTests

  build:
    commands:
      - echo "Running tests and generating JaCoCo coverage..."
      - mvn test
      - echo "Generating JaCoCo report..."
      - mvn jacoco:report
      - echo "Verifying if the JaCoCo report is generated..."
      - ls -lah target/site/jacoco/

  post_build:
    commands:
      - echo "Build and analysis completed!"

artifacts:
  files:
    - target/site/jacoco/**/*
  discard-paths: no
